/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/ping": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example Pong! */
                            message: string;
                            timestamp: number;
                            rnd: number;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/local/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login with email and password */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: email */
                        email: string;
                        password: string;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                302: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Standard Error Response */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "statusCode": 500,
                         *       "error": "Internal Server Error",
                         *       "message": "There was an error processing your request"
                         *     }
                         */
                        "application/json": {
                            statusCode: number;
                            error: string;
                            message: string;
                        };
                    };
                };
                /** @description Standard Error Response */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "statusCode": 500,
                         *       "error": "Internal Server Error",
                         *       "message": "There was an error processing your request"
                         *     }
                         */
                        "application/json": {
                            statusCode: number;
                            error: string;
                            message: string;
                        };
                    };
                };
                /** @description Standard Error Response */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "statusCode": 500,
                         *       "error": "Internal Server Error",
                         *       "message": "There was an error processing your request"
                         *     }
                         */
                        "application/json": {
                            statusCode: number;
                            error: string;
                            message: string;
                        };
                    };
                };
                /** @description Standard Error Response */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "statusCode": 500,
                         *       "error": "Internal Server Error",
                         *       "message": "There was an error processing your request"
                         *     }
                         */
                        "application/json": {
                            statusCode: number;
                            error: string;
                            message: string;
                        };
                    };
                };
                /** @description Standard Error Response */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "statusCode": 500,
                         *       "error": "Internal Server Error",
                         *       "message": "There was an error processing your request"
                         *     }
                         */
                        "application/json": {
                            statusCode: number;
                            error: string;
                            message: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/local/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register a new user account */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: email */
                        email: string;
                        password: string;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                302: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Standard Error Response */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "statusCode": 500,
                         *       "error": "Internal Server Error",
                         *       "message": "There was an error processing your request"
                         *     }
                         */
                        "application/json": {
                            statusCode: number;
                            error: string;
                            message: string;
                        };
                    };
                };
                /** @description Standard Error Response */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "statusCode": 500,
                         *       "error": "Internal Server Error",
                         *       "message": "There was an error processing your request"
                         *     }
                         */
                        "application/json": {
                            statusCode: number;
                            error: string;
                            message: string;
                        };
                    };
                };
                /** @description Standard Error Response */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "statusCode": 500,
                         *       "error": "Internal Server Error",
                         *       "message": "There was an error processing your request"
                         *     }
                         */
                        "application/json": {
                            statusCode: number;
                            error: string;
                            message: string;
                        };
                    };
                };
                /** @description Standard Error Response */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "statusCode": 500,
                         *       "error": "Internal Server Error",
                         *       "message": "There was an error processing your request"
                         *     }
                         */
                        "application/json": {
                            statusCode: number;
                            error: string;
                            message: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/ticket/consume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Exchange a ticket for authentication tokens */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /**
                         * Format: uuid
                         * @description The temporary exchange ticket
                         */
                        ticket: string;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            accessToken: string;
                            refreshToken: string;
                        };
                    };
                };
                /** @description Standard Error Response */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "statusCode": 500,
                         *       "error": "Internal Server Error",
                         *       "message": "There was an error processing your request"
                         *     }
                         */
                        "application/json": {
                            statusCode: number;
                            error: string;
                            message: string;
                        };
                    };
                };
                /** @description Standard Error Response */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "statusCode": 500,
                         *       "error": "Internal Server Error",
                         *       "message": "There was an error processing your request"
                         *     }
                         */
                        "application/json": {
                            statusCode: number;
                            error: string;
                            message: string;
                        };
                    };
                };
                /** @description Standard Error Response */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "statusCode": 500,
                         *       "error": "Internal Server Error",
                         *       "message": "There was an error processing your request"
                         *     }
                         */
                        "application/json": {
                            statusCode: number;
                            error: string;
                            message: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/twitch/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Twitch OAuth callback handler
         * @description Exchanges the Twitch authorization code for a user session
         */
        get: {
            parameters: {
                query: {
                    /** @description The authorization code returned by Twitch */
                    code: string;
                    /** @description The state parameter to prevent CSRF */
                    state: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                302: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Standard Error Response */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "statusCode": 500,
                         *       "error": "Internal Server Error",
                         *       "message": "There was an error processing your request"
                         *     }
                         */
                        "application/json": {
                            statusCode: number;
                            error: string;
                            message: string;
                        };
                    };
                };
                /** @description Standard Error Response */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "statusCode": 500,
                         *       "error": "Internal Server Error",
                         *       "message": "There was an error processing your request"
                         *     }
                         */
                        "application/json": {
                            statusCode: number;
                            error: string;
                            message: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ErrorResponse
         * @description Standard Error Response
         * @example {
         *       "statusCode": 500,
         *       "error": "Internal Server Error",
         *       "message": "There was an error processing your request"
         *     }
         */
        ErrorResponse: {
            statusCode: number;
            error: string;
            message: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
